In [3]:
import Pkg
Pkg.add("EllipsisNotation")
Pkg.add("BenchmarkTools")

using Random
using EllipsisNotation
using BenchmarkTools

# Create random number generator
seed = 1234;
Random.seed!(seed);

 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
 [no changes]
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]
 Resolving package versions...
  Updating `~/.julia/environments/v1.3/Project.toml`
  [6e4b80f9] + BenchmarkTools v0.4.3
  Updating `~/.julia/environments/v1.3/Manifest.toml`
 [no changes]


┌ Info: Precompiling BenchmarkTools [6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf]
└ @ Base loading.jl:1273


In [4]:
N = 3
x = rand(N)
y = rand(N)
@benchmark x .+ y

BenchmarkTools.Trial: 
  memory estimate:  160 bytes
  allocs estimate:  3
  --------------
  minimum time:     266.921 ns (0.00% GC)
  median time:      272.239 ns (0.00% GC)
  mean time:        304.758 ns (3.46% GC)
  maximum time:     12.797 μs (95.92% GC)
  --------------
  samples:          10000
  evals/sample:     318

In [7]:
@benchmark x + y

BenchmarkTools.Trial: 
  memory estimate:  112 bytes
  allocs estimate:  1
  --------------
  minimum time:     53.353 ns (0.00% GC)
  median time:      68.394 ns (0.00% GC)
  mean time:        95.371 ns (19.19% GC)
  maximum time:     75.857 μs (99.79% GC)
  --------------
  samples:          10000
  evals/sample:     984

In [10]:
div(5, 2)

2

In [5]:
t1 = time_ns()
t2 = time_ns()
println(typeof(t1))
println(t2-t1)

UInt64
426703


In [6]:
a = ones(Float64, 2, 3)
reshape(a, -1)

DimensionMismatch: DimensionMismatch("new dimensions (-1,) must be consistent with array size 6")

In [9]:
x = (1,)
y = (2,)
(x..., y...)

(1, 2)

In [36]:
data_type = typeof(a[1]) 

Array{Float64,1}

In [ ]:
Array{data_type}

In [33]:
Array{Array{Float64},1}

Array{Array{Float64,N} where N,1}

In [26]:
Array{typeof(a[1])

Array{Float64,1}

In [4]:
for i in 1:4
    a[i] = i * ones(Float64, 2)
end

In [14]:
aa = collect(Iterators.flatten(a))

8-element Array{Float64,1}:
 1.0
 1.0
 2.0
 2.0
 3.0
 3.0
 4.0
 4.0

In [47]:
Float64 <: AbstractArray

false

In [51]:
a = Array{Float64,1}[[1.0, 1.0], [1.0, 1.0]]
size(a[1])

(2,)

In [52]:
 collect(Iterators.flatten(a))

4-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0

In [5]:
N = 2
a = [zeros(Float64, N) for i in 1:10]
a[1][:] .= -1
a

10-element Array{Array{Float64,1},1}:
 [-1.0, -1.0]
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  

In [6]:
trunc(int,ceil(123/10))

UndefVarError: UndefVarError: int not defined

In [7]:
all([0, 0] .< [1, 1])

true

In [8]:
a = [Set{Int8}() for _ in 1:10]

10-element Array{Set{Int8},1}:
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])
 Set([])

In [9]:
trunc(Int, 10/3)

3

In [10]:
a = Set{Int8}([1, 3, 4])

Set(Int8[4, 3, 1])

In [11]:
a = [0.1, 0.2]

2-element Array{Float64,1}:
 0.1
 0.2

In [12]:
a .^ 4

2-element Array{Float64,1}:
 0.00010000000000000002
 0.0016000000000000003 

In [13]:
using Test
@test 1==-1

Test Failed at In[13]:2
  Expression: 1 == -1
   Evaluated: 1 == -1


Test.FallbackTestSetException: There was an error during testing

In [14]:
i, j = b[1:end]

UndefVarError: UndefVarError: b not defined

In [15]:
i = 1
"A{$i+1}"

"A{1+1}"

In [16]:
a = []


0-element Array{Any,1}

In [17]:
num_sites = 10
num_steps = 100
beta = 100.0

J = 1.0 # FM
#J = -1.0 # AFM

spins = rand([-1, 1], num_sites)
println(spins)

function energy(spins)
    ene = 0.0
    for isite = 1:num_sites
        ene -= spins[isite] * spins[isite+1]
    end
    return ene * J
end

# H = - s * h
function effective_field(spins, isite)
    if isite == 1
        return J * spins[1]
    elseif isite == length(spins)
        return J * spins[isite-1]
    else
        return J * (spins[isite-1] + spins[isite+1])
    end
end

for step = 1:num_steps
    target_site = rand(1:num_sites)
    # Eud = E(up) - E(down) = - 2 * h
    ene_ud = - 2 * effective_field(spins, target_site)
    prob_up = 1/(1 + exp(beta * ene_ud))
    if rand() < prob_up
        spins[target_site] = 1
    else
        spins[target_site] = -1
    end
end

[-1, 1, 1, 1, -1, -1, -1, 1, -1, 1]


In [18]:
println(spins)

[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]


In [19]:
struct SingleSpinFlipUpdater
    num_Jij::Int
    num_spins::Int
    connection::Array{Int,2}
    coord_num::Array{Int,2}
end

In [20]:
function compute_energy(spins:::Array{Int64})
    #return -sum([intr[3] * spins[intr[1]] * spins[intr[2]] for intr in model.Jij])
    return 0.0
end

TypeError: TypeError: in Type{...} expression, expected UnionAll, got Symbol

In [21]:
energy = 0.0
println(energy)
for i in 1:10
    energy += 1.0
end

ErrorException: invalid redefinition of constant energy

In [14]:
function display_percent_bad(x)
     if x isa AbstractString
        if occursin(r"^\d*\.?\d+%$", x)  # any combination of numbers, followed by a percent sign
            println(x)
        else
            throw(DomainError(x, "Not valid percentage format"))
        end
    else
        println(100x, "%")
    end
end

struct Half
end

In [20]:
function display_percent_bad(x)
    if x isa AbstractString
        println("X")
    else
        println(100x)
    end
end

struct Half
end

In [21]:
display_percent_bad("5.3%")
display_percent_bad(0.5)
display_percent_bad(Half())

X
50.0


MethodError: MethodError: no method matching *(::Int64, ::Half)
Closest candidates are:
  *(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  *(::T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}, !Matched::T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:54
  *(::Union{Int16, Int32, Int64, Int8}, !Matched::BigInt) at gmp.jl:463
  ...

In [24]:
Float64 <: AbstractFloat

true

In [26]:
abstract type Scalarness end
struct Scalar <: Scalarness end
struct NonScalar <: Scalarness end

scalarness(::Type) = Scalar() #fall-back, by default everything is scalar
scalarness(::Type{<:AbstractArray}) = NonScalar()
scalarness(::Type{<:Tuple}) = NonScalar()
scalarness(::Type{<:AbstractString}) = NonScalar()

scalarness (generic function with 4 methods)

In [28]:
scalarness(typeof(1.0))

Scalar()

In [30]:
aslist(x::T) where T = aslist(scalarness(T), x)

aslist(::Scalar, x) = [x]
aslist(::NonScalar, x) = x

@show aslist([1,2,3])
@show aslist(1);
@show aslist(Set([1,2]));

aslist([1, 2, 3]) = [1, 2, 3]
aslist(1) = [1]
aslist(Set([1, 2])) = Set{Int64}[Set([2, 1])]


In [31]:
catty = fill(Basic(:🐱), 2, 2)

UndefVarError: UndefVarError: Basic not defined